### ISSUE TITLE
Is there a reason to not use Go's qsufsort implementation? 

### ISSUE THREAD

**Issue by c4milo** [kr/binarydist#3]
https://golang.org/src/index/suffixarray/qsufsort.go

**Comment by kr** [comment]
Oh, nice. Thanks for the pointer!

Had I known about index/suffixarray when I wrote this, I probably would have used it. Instead, I just translated the original bsdiff and bspatch C code nearly line for line. Now it seems to work fine as-is, so really the question is, is there a reason to switch to index/suffixarray? I don't see anything compelling.
