### ISSUE TITLE
Undoing patches

### ISSUE THREAD

**Issue by amlwwalker** [kr/binarydist#6]
Hi,

I am looking to use bsdiff to keep a record of the changes I make to a file. As I see it, I keep the original file and then I can keep patching all the diffs to that file to get to the current state of that file. However I have been wondering if I can go the other way around and if I have the current state of the file, can I "strip" off patches and get back to the original state of the file? I don't know if that reads sensically at all!
If I have a file, let's call them v0.x for example,
V0.1
V0.2
V0.3

Then bsdiff will give me the diffs between each version. If I then have v0.1 I can patch it twice to get to v0.3. 
However if I have v0.3 is there a way I can patch it to get back to v0.2 and therefrom 0.1?
I have the diff between v0.2 and v0.3 but I guess that's not the same as having the diff of v0.3 and v0.2 is it? 
I had wondered if there was a nifty XOR of the diff or something that could be done to go backwards??

I would appreciate any help you can give. Thanks

Alex

**Comment by kr** [comment]
According to Colin Percival (designer of bsdiff), it is [not possible](https://twitter.com/cperciva/status/581217879170936833):

> In case anyone was wondering: bspatch doesn't have a -R option because making bsdiff patches reversible would make them considerably larger.

But if you wanted, instead of producing one patch (from V0.1 to V0.2), you could produce two patches (going in both directions), and then use whichever one you need in a given situation.

I hope this helps!

**Comment by kr** [comment]
P.S. Here's why.

There are two important operations a binary patch does: insert some bytes and delete some bytes. (There can be other operations, but at least we need these two.)

When inserting bytes, the patch needs to tell us the bytes to be inserted, as well as where to put them. For example, if v1 is `go west`, the patch "insert `south` at position 3" would produce `go southwest` as v2.

When deleting bytes, it can save space by saying how *many* bytes to be deleted, as well as where to delete them, without repeating the deleted bytes themselves. For example, with v2 `go southwest`, the patch "delete 4 bytes at position 8" would produce `go south` as v3.

To reverse a patch, we swap "insert" and "delete". For the first patch above, that's easy. We change it to "delete 5 bytes at position 3". Applying this to v2 gives us v1 again. But for the other patch, what do we do? We know it should look like "insert `XXXX` at position 8" but what are those 4 bytes? If all we have is v3 and the un-reversed patch, we don't know what to put in the `XXXX` part.
